words = {"Russia": "Россия",
         "USA": "США",
         "Afghanistan": "Афганистан",
         "Albania": "Албания",
         "Algeria": "Алжир",
         "Andorra": "Андорра",
         "Angola": "Ангола",
         "Argentina": "Аргентина",
         "Armenia": "Армения",
         "Australia": "Австралия",
         "Austria": "Австрия",
         "Azerbaijan": "Азербайджан",
         "The Bahamas": "Багамы",
         "Bahrain": "Бахрейн",
         "Bangladesh": "Бангладеш",
         "Barbados": "Барбадос",
         "Belarus": "Беларусь",
         "Belgium": "Бельгия",
         "Belize": "Белиз",
         "Benin": "Бенин"}